[package]
name = "keyboard-statistics"
version = "0.1.0"
edition = "2024"

[dependencies]
inputbot = "0.6"
windows = { 
    version = "0.48", 
    features = [
        "Win32_UI_Input_Ime",
        "Win32_UI_WindowsAndMessaging", 
        "Win32_Foundation",
        "Win32_Globalization"
    ] 
}
