name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install
          rustup target add x86_64-pc-windows-msvc

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          npm install
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          
      - name: Check icon files (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          if (Test-Path "src-tauri/icons/icon.ico") {
            Write-Host "icon.ico file exists."
            Get-ChildItem -Path "src-tauri/icons" -Force
          } else {
            Write-Host "icon.ico file is missing!" -ForegroundColor Red
            [System.Environment]::Exit(1)
          }
          
      - name: Check icon files (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          if [ -f "src-tauri/icons/icon.ico" ]; then
            echo "icon.ico file exists."
            ls -la src-tauri/icons/
          else
            echo "icon.ico file is missing!"
            exit 1
          fi

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'App v__VERSION__'
          releaseBody: '请查看 GitHub releases 页面查看更新内容。'
          releaseDraft: true
          prerelease: false
          iconPath: src-tauri/icons/icon.ico